
# travis-ci.com
language: julia
julia:
  - nightly
  - 1.1
  - 1.0
codecov: true

matrix:
  allow_failures:
    - julia: nightly

## Create Documentation 
jobs:
  include:
    - stage: "Documentation"
      julia: 1.0
      os: linux
      script:
        - julia -e 'using Pkg;
              Pkg.activate(".");
              Pkg.instantiate();'
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip


script:
  - julia --color=yes -e 'using Pkg; Pkg.activate(); Pkg.instantiate(); Pkg.test()'
